[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "ntrip_client"
version = "3.0.0"
description = "NTRIP client for the ANELLO ROS2 driver"
license = {text = "MIT"}
maintainers = [{name = "Austin Johnson", email = "austin.johnson@anellophotonics.com"}]
keywords = ["ROS2", "NTRIP", "GNSS"]
requires-python = ">=3.10"

[project.scripts]
ntrip_ros = "ntrip_client.ntrip_ros:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.data-files]
"share/ament_index/resource_index/packages" = ["resource/ntrip_client"]
"share/ntrip_client" = ["package.xml"]
